### ISSUE TITLE
Много вкладок с настройками

### ISSUE THREAD

**Issue by MarisKori** [yarkovaleksei/toster-extension#123]
**Описание проблемы**
При нажатии на иконку открываются настройки - второе окно. Сколько кликнешь, столько и вкладок.

**Ожидаемое поведение**
Если вкладка с настройками уже открыта, то происходит переключение на неё.

**ОС и браузер**
 - Операционная система: Windows
 - Браузер Google Chrome
 - Версия приложения Последняя

**Comment by yarkovaleksei** [comment]
Оу, как-то и не подумал об этом. @MarisKori  спасибо за обратную связь!
